services:
  postgres:
    image: postgres:16
    container_name: gamefinder_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gamefinder_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gamefinder_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    networks:
      - gamefinder_network

  backend:
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gamefinder_backend
    restart: unless-stopped
    environment:
      PORT: ${BACKEND_PORT}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    networks:
      - gamefinder_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gamefinder_frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - gamefinder_network

  nginx:
    image: nginx:alpine
    container_name: gamefinder_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - gamefinder_network
  
  recommendation:
    build:
      context: ./recommendation
      dockerfile: Dockerfile
    environment:
        - DATABASE_URL=${DATABASE_URL}
    depends_on:
        - backend
        - postgres
    networks: 
        - gamefinder_network
    ports:
        - "8001:8001"

  prometheus:
    image: prom/prometheus
    container_name: gamefinder_prometheus
    restart: unless-stopped
    ports: 
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - gamefinder_network

  grafana:
    image: grafana/grafana
    container_name: gamefinder_grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - gamefinder_network
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: false
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
  
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: gamefinder_postgres_exporter
    restart: unless-stopped
    volumes:
      - ./prometheus/queries.yaml:/queries.yaml:ro
    environment:
      DATA_SOURCE_NAME: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      PG_EXPORTER_EXTEND_QUERY_PATH: /queries.yaml
    depends_on:
      - postgres
    ports: #for testing purpose, rm after -- no need to expose this, accessible from within
      - "9187:9187"
    networks:
      - gamefinder_network
  
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: gamefinder_nginx_exporter
    restart: unless-stopped
    networks:
      - gamefinder_network
    depends_on:
      - nginx
    command: --nginx.scrape-uri=http://nginx:80/stub_status
    ports: #testing purpose only, rm after -- same as postgres exporter.
      - "9113:9113"

  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: gamefinder_blackbox_exporter
    restart: unless-stopped
    networks:
      - gamefinder_network
    depends_on:
      - backend

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  gamefinder_network:
    driver: bridge