apiVersion: 1

groups:
  - orgId: 1
    name: GameFinder infrastructure
    folder: GameFinder
    interval: 1m
    rules:

      # Exporter unreacheable
      - uid: gf-exporter-down
        title: Monitoring exporter down
        condition: B
        data:
          - refId: A
            relativeTimeRange: { from: 300, to: 0 }
            datasourceUid: prometheus
            model:
              expr: 'up{job=~"postgres|nginx"}'
              instant: true
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              type: classic_conditions
              conditions:
                - evaluator: { type: lt, params: [1] }
                  operator: { type: and }
                  query: { params: [A] }
                  reducer: { type: min }
              refId: B
        noDataState: NoData
        execErrState: Error
        for: 2m
        annotations:
          summary: "One prometheus exporter is down"
          description: "An exporter (postgres or nginx) has been unreachable for 2 minutes. Check your containers."
        labels:
          severity: critical

      # PostgreSQL status
      - uid: gf-postgres-status
        title: PostgreSQL status
        condition: B
        data:
          - refId: A
            relativeTimeRange: { from: 300, to: 0 }
            datasourceUid: prometheus
            model:
              expr: pg_up
              instant: true
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              type: classic_conditions
              conditions:
                - evaluator: { type: lt, params: [1] }
                  operator: { type: and }
                  query: { params: [A] }
                  reducer: { type: last }
              refId: B
        noDataState: NoData
        execErrState: Error
        for: 60s
        annotations:
          summary: PostgreSQL is down.
          description: The DB is down. Check your container.
        labels:
          severity: critical
