events 
{
	worker_connections 1024;
}

http 
{
	# Future frontend proxy
	# server 
	# {
	# 	listen 80;
	# 	location / 
	# 	{
	# 		proxy_pass http://frontend:5173;
	# 	}
	# }

	# Future backend proxy
	# server 
	# {
	# 	listen 80;
	# 	location /api 
	# 	{
	# 		proxy_pass http://backend:3001;
	# 	}
	# }

	# Placeholder page
	server 
	{
		listen 80 default_server;
		
		location / 
		{
			return 200 'Transcendence Infrastructure Ready!\n';
			add_header Content-Type text/plain;
		}
	}
}